### ISSUE TITLE
With Double Chests only one side gets locked

### ISSUE THREAD

**Issue by jmiahman** [prism/Keys#10]
With double chests only one side of the chest gets locked. See Screenshot..
![half-locked](https://cloud.githubusercontent.com/assets/448754/13131174/00458fb2-d5a7-11e5-94b1-93037bd58985.png)

Oops this looks like a duplicate of #6

**Comment by viveleroi** [comment]
Both sides are locked if you place each but if you `/lock` one side the other isn't captured. I'll close this in favor of the other one.
