### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by GershonR** [prism/Keys#16]
Occasionaly getting this error popup on the console:
http://pastebin.com/s4wWXRvN

**Comment by GershonR** [comment]
Any update on this? It's still spamming the console for me

**Comment by Ollie2000** [comment]
pastebin has been removed, please make another one. Viveleroi or whoever else works on this might not have seen the error.

**Comment by GershonR** [comment]
`07.05 11:36:24 [Server] Server thread/ERROR [Sponge]: Could not pass InteractBlockEvent$Secondary$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@15afe73d
07.05 11:36:24 [Server] INFO java.util.NoSuchElementException: No value present
07.05 11:36:24 [Server] INFO at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_92]
07.05 11:36:24 [Server] INFO at com.helion3.keys.listeners.InteractBlockListener.onUse(InteractBlockListener.java:49) ~[InteractBlockListener.class:1.2+unknown-b0.git-unknown]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.event.listener.SecondaryListener_InteractBlockListener_onUse157.handle(Unknown Source) ~[?:?]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:217) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:202) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:244) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:229) [SpongeModEventManager.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) [SpongeImpl.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:606) [SpongeCommonEventFactory.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:601) [SpongeCommonEventFactory.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:520) [lm.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) [ja.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) [ja.class:?]
07.05 11:36:24 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:107) [PacketUtil.class:1.8.9-1855-4.1.0-BETA-1311]
07.05 11:36:24 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
07.05 11:36:24 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
07.05 11:36:24 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
07.05 11:36:24 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
07.05 11:36:24 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
07.05 11:36:24 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]`

**Comment by viveleroi** [comment]
This has already been resolved but to due a hard drive failure I have not yet been able to push the changes.

**Comment by GershonR** [comment]
Are you able to push out the update anytime soon? The error messages is really annoying and takes up most of the console

**Comment by viveleroi** [comment]
The extra commit was pushed a few weeks ago I just haven't put out a new release. I can try to do that this week, I need to build against latest sponge anyway.

**Comment by GershonR** [comment]
Ok looking forward to it then

**Comment by viveleroi** [comment]
https://github.com/prism/Keys/releases/tag/1.2.1

**Comment by GershonR** [comment]
Thanks for the update, will there be any updates to the plugin too?
