### ISSUE TITLE
Users able to bypass doors with Latest Forge, SpongeForge and Keys

### ISSUE THREAD

**Issue by jsnbrown1989** [prism/Keys#19]
My users have documented that if they spam the doors, they can manage to access through them. They have also reported that if they warp to an area with doors that are locked, they can walk right in as if there was no protection plugin even there for a short period of time. 

Server doesn't experience lag much as there are only a few players on at a time and its running on 8 gigs of ram. Granted its a pixelmon server but spawn rates are down low.

**Comment by viveleroi** [comment]
Keys doesn't process anything asynchronously so I don't see how this would be possible unless it's a sponge issue. I can't reproduce this on the latest bleeding branch of Sponge. If you have specific steps to reproduce this, let me know.
